#!/usr/bin/env python3
"""Generate a synthetic emanote notebook of ~4500 markdown files, ~70MB total.

Each file has:
- A title heading
- A YAML frontmatter sometimes
- Several paragraphs of lorem-like text with wikilinks
- A few headings
- Some inline code, occasional list, occasional code block

Wikilinks form a random graph so the link index actually has work to do.
"""
import os, random, sys, hashlib, string

random.seed(42)

OUT = sys.argv[1] if len(sys.argv) > 1 else "/home/toor/corpus"
N = int(sys.argv[2]) if len(sys.argv) > 2 else 4500
TARGET_BYTES = int(sys.argv[3]) if len(sys.argv) > 3 else 70 * 1024 * 1024
AVG_BYTES = TARGET_BYTES // N

WORDS = ("the quick brown fox jumps over the lazy dog functor monad applicative haskell "
         "pandoc emanote ema lvar parser source eval render template heist note ix set "
         "memory leak profile retainer cost centre static unboxed strict thunk graph link "
         "wikilink folgezettel sequel zettel obsidian roam neuron foam dendron logseq "
         "atomic note structure architecture optimisation cycle measurement baseline "
         "decision dependency volatility encapsulation closure capture share unsharing").split()

TAGS_POOL = ["haskell", "design", "perf", "note", "todo", "idea", "ref", "math", "wip", "draft",
             "review", "meta", "tool", "lit", "code", "infra", "ux", "ops", "test", "spec"]

def folder_for(i):
    # 32 top-level folders, optional nested
    top = f"topic{i % 32:02d}"
    if i % 7 == 0:
        return os.path.join(top, f"sub{(i // 32) % 11}")
    return top

def slug(i):
    return f"n{i:05d}"

def title(i):
    return " ".join(random.sample(WORDS, k=random.randint(2, 5))).title()

def paragraph(words=120):
    out = []
    while sum(len(w) for w in out) + len(out) < words:
        out.append(random.choice(WORDS))
    s = " ".join(out)
    return s[0].upper() + s[1:] + "."

def wikilink(target_i, alias=None):
    t = slug(target_i)
    if alias:
        return f"[[{t}|{alias}]]"
    return f"[[{t}]]"

def write_file(i, n, path):
    has_fm = (i % 3 != 0)
    lines = []
    if has_fm:
        tags = random.sample(TAGS_POOL, k=random.randint(0, 4))
        lines.append("---")
        lines.append(f"title: {title(i)}")
        if tags:
            lines.append("tags:")
            for t in tags:
                lines.append(f"  - {t}")
        if i % 13 == 0:
            lines.append(f"order: {i % 50}")
        lines.append("---")
        lines.append("")
    lines.append(f"# {title(i)}")
    lines.append("")
    # body — keep generating paragraphs until size ~ AVG_BYTES
    target = max(2000, int(random.gauss(AVG_BYTES, AVG_BYTES / 4)))
    while sum(len(x) for x in lines) < target:
        kind = random.random()
        if kind < 0.55:
            p = paragraph(random.randint(40, 180))
            # sprinkle wikilinks
            tokens = p.split()
            for _ in range(random.randint(1, 4)):
                j = random.randrange(len(tokens))
                target_i = random.randrange(n)
                alias = tokens[j] if random.random() < 0.5 else None
                tokens[j] = wikilink(target_i, alias)
            lines.append(" ".join(tokens))
            lines.append("")
        elif kind < 0.7:
            lines.append(f"## {title(i)}")
            lines.append("")
        elif kind < 0.82:
            # list
            for _ in range(random.randint(3, 8)):
                lines.append(f"- {paragraph(random.randint(8, 25))}")
            lines.append("")
        elif kind < 0.92:
            # code block
            lines.append("```haskell")
            lines.append(f"foo{i} :: Int -> Int")
            lines.append(f"foo{i} x = x + {i}")
            lines.append("```")
            lines.append("")
        else:
            # embedded note (becomes processed)
            lines.append(f"![[{slug(random.randrange(n))}]]")
            lines.append("")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines))

def main():
    os.makedirs(OUT, exist_ok=True)
    # an index.md at root
    with open(os.path.join(OUT, "index.md"), "w") as f:
        f.write("# Synthetic Corpus\n\nGenerated by gen_corpus.py for emanote #66 reproduction.\n")
    for i in range(N):
        rel = os.path.join(folder_for(i), slug(i) + ".md")
        write_file(i, N, os.path.join(OUT, rel))
    # report
    total = 0
    count = 0
    for root, _, files in os.walk(OUT):
        for f in files:
            if f.endswith(".md"):
                total += os.path.getsize(os.path.join(root, f))
                count += 1
    print(f"Wrote {count} files, {total/1024/1024:.1f} MB total", flush=True)

if __name__ == "__main__":
    main()
