<footer class="flex items-center justify-center mt-2 mb-8 space-x-4 text-center text-gray-800">
  <div class="flex space-x-2">
    <div>Generated by <a class="font-bold" href="https://note.ema.srid.ca/">Emanote</a>
      <ema:metadata>
        <with var="template">
          <span class="font-mono text-sm tracking-tighter" title="And rendered with ${value:name}">
            <ema:version />
          </span>
        </with>
      </ema:metadata>
    </div>
  </div>
</footer>