<footer class="flex items-center justify-center mt-2 mb-8 space-x-4 text-center text-gray-500">
  <div class="flex space-x-2">
    <div><a class="font-bold" href="@index">@Index</a></div>
    <div>|</div>
    <div>Generated by <a class="font-bold" href="https://note.ema.srid.ca/">Emanote</a>
      <span class="font-mono text-sm tracking-tighter">
        <ema:version />
      </span>
    </div>
    <div>|</div>
    <div><a class="font-bold" href="@tags">@Tags</a></div>
  </div>
</footer>