<footer class="flex items-center justify-center mt-2 mb-8 space-x-4 text-center text-gray-800">
  <div>
    <a href="">
      <svg xmlns="http://www.w3.org/2000/svg" class="${iconSize} inline" fill="none"
        viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
      </svg>
    </a>
  </div>
  <div>
    Generated by <a class="font-bold" href="https://note.ema.srid.ca/">Emanote</a>
    <ema:metadata>
      <with var="template">
        <span class="font-mono text-sm tracking-tighter" title="And rendered with ${value:name}">
          <ema:version />
        </span>
      </with>
    </ema:metadata>
  </div>
  <div>
    <a href="${ema:indexUrl}" title="View Index">
      <svg style="width: 1rem;" class="hover:text-${theme}-700" fill="none" stroke="currentColor"
        viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4">
        </path>
      </svg>
    </a>
  </div>
  <div>
    <a href="${ema:note:editUrl}" title="Edit this page" rel="edit">
      <svg style="width: 1rem;" class="hover:text-${theme}-700" fill="none" stroke="currentColor"
        viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
          clip-rule="evenodd"></path>
      </svg>
    </a>

  </div>
</footer>