#+TITLE: Org Mode ✍️

Emanote provides first-class support for [[file:markdown.md][Markdown]]. But it also supports secondary formats (albeit not necessarily with the same level of support) beginning with [[https://orgmode.org/][Org Mode]]. See Pandoc's [[https://pandoc.org/org.html][Org section]] for information on controlling the parsing.

**WARNING**: This is a =🧪 beta 🧪= feature.

** Linking
Org Mode has no notion of wiki-links, but you can use =file:= [[https://orgmode.org/guide/Hyperlinks.html][hyperlinks]] to link to other files such as Markdown files. If you wish to link to a .org file from a Markdown file, however, regular wiki-links ought to work.

** Syntax
Here is a handpicked selection of syntatic features of Org Mode as particularly known to work on Emanote.

*** Code blocks 

See [[file:../tips/js/syntax-highlighting.md][Syntax Highlighting]] for general information.

#+NAME: factorial
#+BEGIN_SRC haskell :results silent :exports code :var n=0
  fac 0 = 1
  fac n = n * fac (n-1)
#+END_SRC

*** LaTeX 

See [[file:../tips/js/math.md][Math]] for general information.

The radius of the sun is R_sun = 6.96 x 10^8 m.  On the other hand,
the radius of Alpha Centauri is R_{Alpha Centauri} = 1.28 x R_{sun}.

\begin{equation}                        % arbitrary environments,
x=\sqrt{b}                              % even tables, figures
\end{equation}

If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \]

** Limitations
- While =#+TITLE= is recognized, other metadata are not recognized (yet). Therefore you must store file-associated metadata in a separate [[file:yaml-config.md][YAML file]].
