<footer class="flex items-center justify-center mt-10 mb-10">
  <div class="inline-flex items-center justify-center space-x-6 px-8 py-4 bg-gray-50 dark:bg-gray-900 rounded-lg">
    <bind tag="iconClass">w-8 h-8 text-gray-600 dark:text-gray-400 hover:text-${theme}-600 dark:hover:text-${theme}-400 hover:bg-${theme}-50 dark:hover:bg-${theme}-950 p-1.5 rounded-md transition-all hover:shadow-md hover:-translate-y-0.5</bind>
  <div>
    <ema:metadata>
      <with var="template">
        <a href="${value:baseUrl}" title="Go to Home">
          <svg xmlns="http://www.w3.org/2000/svg" class="${iconClass}" fill="none"
            viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
          </svg>
        </a>
      </with>
    </ema:metadata>
  </div>
  <div>
    <a href="${ema:indexUrl}" title="View Index">
      <svg xmlns="http://www.w3.org/2000/svg" class="${iconClass}" fill="none" viewBox="0 0 24 24"
        stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
      </svg>
    </a>
  </div>
  <div>
    <a href="https://emanote.srid.ca" target="_blank" title="Generated by Emanote ${ema:version}">
      <img class="${iconClass}" src="${ema:emanoteStaticLayerUrl}/emanote-logo.svg"
        alt="Emanote logo" />
    </a>
  </div>
  <div>
    <a href="${ema:tagIndexUrl}" title="View tags">
      <svg class="${iconClass}" fill="none" stroke="currentColor" viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z">
        </path>
      </svg>
    </a>
  </div>
  <div>
    <a href="${ema:taskIndexUrl}" title="View tasks">
      <svg xmlns="http://www.w3.org/2000/svg" class="${iconClass}" fill="none" viewBox="0 0 24 24"
        stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    </a>
  </div>
  </div>
</footer>